### ISSUE TITLE
EventSource close()d during 'reconnect' comes alive again after retry timeout

### ISSUE THREAD

**Issue by gclinch** [lukas-reining/eventsource#11]
When a working EventSource is failed (by the remote end closing the connection), reconnect() is called internally as expected.

reconnect() checks whether readyState has been set to CLOSED (it hasn't), and then queues a call to connect() after a timeout:
https://github.com/lukas-reining/eventsource/blob/14c16b6ad4033b16f96da4df8f1529bca2c01b2e/src/eventsource.ts#L168

Before the timeout expires, the consuming application calls close(), which changes the readyState to CLOSED.

Once the timeout expires, connect() resets readyState to CONNECTING:
https://github.com/lukas-reining/eventsource/blob/14c16b6ad4033b16f96da4df8f1529bca2c01b2e/src/eventsource.ts#L71

.. and the previously closed EventSource begins emitting messages.

A quick fix might be to test readyState early in connect() or to store the timeoutID returned by reconnect()'s setTimeout() and call clearTimeout() during close().

**Comment by lukas-reining** [comment]
Hey @gclinch, thanks for submitting the issue.
Sorry for the late response, have been at conference the whole week. 

This makes sense and I like your solution ideas. I guess checking if the status is closed in the beginning of the `reconnect` function should be a good fix. Calling lose while reconnecting will be okay because of the `AbortController` will just cancel the request then.

As I am traveling I will only be able to fix it until mid of next week so if you can change it before feel free to open up a PR, otherwise I will do it then.

**Comment by lukas-reining** [comment]
Hey @gclinch,
I just pushed a fix for this in version `1.4.9`.
Both options you proposed seemed good and I decided to go with both.
Generally clearing the timeout should be fine but to be really sure I also check the state being closed before connecting.
Thank you very much and please let me know if the fix is suiting your needs.
